### ISSUE TITLE
Write some bread recipe

### ISSUE THREAD

**Issue by Cgg** [feston/recettes#4]
Because this is la base.

**Comment by basilesimon** [comment]
Si tu pouvais avancer sur cette issue, ce serait pas mal, j'ai la dalle. @Cgg

**Comment by Cgg** [comment]
in progress

**Comment by basilesimon** [comment]
T'attends de mettre des photos pour merger?

**Comment by Cgg** [comment]
Oui il faut que je mettes une photo du produit fini au moins (en attendant
mieux) et je veux rajouter quelques footnotes, n'est-ce pas.
